plugins {
    id 'java'
}

group = 'gg.nationsglory'
version = '2.0.0'

compileJava {
    options.encoding = 'UTF-8'
    options.release = 17
}

repositories { mavenCentral() }

jar {
    archiveBaseName = 'mcpc-java17-agent'
    archiveVersion = ''
    manifest {
        attributes(
            'Premain-Class': 'gg.nationsglory.mcpcj17.McpcJava17Agent',
            'Can-Redefine-Classes': 'false',
            'Can-Retransform-Classes': 'false',
            'Implementation-Title': 'MCPC+ Java 17 Agent',
            'Implementation-Version': project.version
        )
    }
}
